[sectors]
NBIS = "Information Technology"
INTC = "Information Technology"
GOOGL = "Communication Services"
META = "Communication Services"
AMZN = "Consumer Discretionary"
TSLA = "Consumer Discretionary"
WMT = "Consumer Staples"
COST = "Consumer Staples"
XOM = "Energy"
CVX = "Energy"
JPM = "Financials"
V = "Financials"
LLY = "Health Care"
JNJ = "Health Care"
GE = "Industrials"
RTX = "Industrials"
NVDA = "Information Technology"
MSFT = "Information Technology"
LIN = "Materials"
SHW = "Materials"
PLD = "Real Estate"
AMT = "Real Estate"
NEE = "Utilities"
SO = "Utilities"