[sectors]
INTC = "Information Technology"
GOOGL = "Communication Services"
META = "Communication Services"
TSLA = "Consumer Discretionary"
WMT = "Consumer Staples"
COST = "Consumer Staples"
NVDA = "Information Technology"
MSFT = "Information Technology"
LIN = "Materials"