symbols = [
	"INTC",

	# Communication Services
	"GOOGL",
	"META",

	# Consumer Discretionary
	"TSLA",

	# Consumer Staples
	"WMT",
	"COST",

	# Information Technology
	"NVDA",
	"MSFT",

	# Materials
	"LIN",
]
